//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSOrderService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AuthenticationInfo : object
    {
        
        private string PasswordField;
        
        private string UserIdField;
        
        private decimal WarehouseIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WarehouseId
        {
            get
            {
                return this.WarehouseIdField;
            }
            set
            {
                this.WarehouseIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportOrder_Order", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class ImportOrder_Order : object
    {
        
        private string AdditionalDataField;
        
        private string[] AttachmentUrlsField;
        
        private System.Nullable<int> CarrierIdField;
        
        private string LanguageField;
        
        private bool MailingAllowedField;
        
        private WMSOrderService.ImportOrder_OrderElement[] OrderElementsField;
        
        private bool PartialDeliveryAllowedField;
        
        private System.Nullable<System.DateTime> PreferredDeliveryDateField;
        
        private string PreferredShipperAccountCodeField;
        
        private string ReferenceField;
        
        private string RemarkField;
        
        private WMSOrderService.ImportOrder_ShippingData ShippingDataField;
        
        private string ShippingInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AttachmentUrls
        {
            get
            {
                return this.AttachmentUrlsField;
            }
            set
            {
                this.AttachmentUrlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CarrierId
        {
            get
            {
                return this.CarrierIdField;
            }
            set
            {
                this.CarrierIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MailingAllowed
        {
            get
            {
                return this.MailingAllowedField;
            }
            set
            {
                this.MailingAllowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.ImportOrder_OrderElement[] OrderElements
        {
            get
            {
                return this.OrderElementsField;
            }
            set
            {
                this.OrderElementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PartialDeliveryAllowed
        {
            get
            {
                return this.PartialDeliveryAllowedField;
            }
            set
            {
                this.PartialDeliveryAllowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PreferredDeliveryDate
        {
            get
            {
                return this.PreferredDeliveryDateField;
            }
            set
            {
                this.PreferredDeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredShipperAccountCode
        {
            get
            {
                return this.PreferredShipperAccountCodeField;
            }
            set
            {
                this.PreferredShipperAccountCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.ImportOrder_ShippingData ShippingData
        {
            get
            {
                return this.ShippingDataField;
            }
            set
            {
                this.ShippingDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingInfo
        {
            get
            {
                return this.ShippingInfoField;
            }
            set
            {
                this.ShippingInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportOrder_ShippingData", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class ImportOrder_ShippingData : object
    {
        
        private string AddressField;
        
        private string BuildingField;
        
        private string CityField;
        
        private string CompanyField;
        
        private string CountryField;
        
        private string CustomerInfoField;
        
        private string DepartmentField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string GenderField;
        
        private string LastNameField;
        
        private string PhoneField;
        
        private string Phone1Field;
        
        private string PostalCodeField;
        
        private string ProvinceField;
        
        private string VATNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building
        {
            get
            {
                return this.BuildingField;
            }
            set
            {
                this.BuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerInfo
        {
            get
            {
                return this.CustomerInfoField;
            }
            set
            {
                this.CustomerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1
        {
            get
            {
                return this.Phone1Field;
            }
            set
            {
                this.Phone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VATNumber
        {
            get
            {
                return this.VATNumberField;
            }
            set
            {
                this.VATNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportOrder_OrderElement", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class ImportOrder_OrderElement : object
    {
        
        private string AdditionalDataField;
        
        private string CustomerCodeField;
        
        private int QuantityField;
        
        private string ReferenceField;
        
        private string RemarkField;
        
        private string[] SerialsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Serials
        {
            get
            {
                return this.SerialsField;
            }
            set
            {
                this.SerialsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportOrderResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class ImportOrderResult : object
    {
        
        private int CodeField;
        
        private WMSOrderService.ImportOrderResult_Order ImportedOrderField;
        
        private string[] MessagesField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.ImportOrderResult_Order ImportedOrder
        {
            get
            {
                return this.ImportedOrderField;
            }
            set
            {
                this.ImportedOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportOrderResult_Order", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class ImportOrderResult_Order : object
    {
        
        private WMSOrderService.ImportOrderResult_OrderElement[] ElementsField;
        
        private int OrderIdField;
        
        private int StatusIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.ImportOrderResult_OrderElement[] Elements
        {
            get
            {
                return this.ElementsField;
            }
            set
            {
                this.ElementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportOrderResult_OrderElement", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class ImportOrderResult_OrderElement : object
    {
        
        private int CodeField;
        
        private string CustomerCodeField;
        
        private int QuantityField;
        
        private string RemarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark
        {
            get
            {
                return this.RemarkField;
            }
            set
            {
                this.RemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderStatusResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class GetOrderStatusResult : object
    {
        
        private int CodeField;
        
        private WMSOrderService.GetOrderStatusResult_Order MainOrderField;
        
        private string[] MessagesField;
        
        private WMSOrderService.GetOrderStatusResult_Order[] SubOrdersField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.GetOrderStatusResult_Order MainOrder
        {
            get
            {
                return this.MainOrderField;
            }
            set
            {
                this.MainOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.GetOrderStatusResult_Order[] SubOrders
        {
            get
            {
                return this.SubOrdersField;
            }
            set
            {
                this.SubOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderStatusResult_Order", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class GetOrderStatusResult_Order : object
    {
        
        private WMSOrderService.GetOrderStatusResult_OrderEvent[] EventsField;
        
        private int OrderIdField;
        
        private int StatusIdField;
        
        private System.DateTime StatusTimeStampField;
        
        private string[] TrackingCodesField;
        
        private string TrackingUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.GetOrderStatusResult_OrderEvent[] Events
        {
            get
            {
                return this.EventsField;
            }
            set
            {
                this.EventsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusTimeStamp
        {
            get
            {
                return this.StatusTimeStampField;
            }
            set
            {
                this.StatusTimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TrackingCodes
        {
            get
            {
                return this.TrackingCodesField;
            }
            set
            {
                this.TrackingCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingUrl
        {
            get
            {
                return this.TrackingUrlField;
            }
            set
            {
                this.TrackingUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderStatusResult_OrderEvent", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class GetOrderStatusResult_OrderEvent : object
    {
        
        private int StatusIdField;
        
        private System.DateTime StatusTimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusTimeStamp
        {
            get
            {
                return this.StatusTimeStampField;
            }
            set
            {
                this.StatusTimeStampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDatedStatusForOrdersResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class GetDatedStatusForOrdersResult : object
    {
        
        private int CodeField;
        
        private string[] MessagesField;
        
        private WMSOrderService.GetDatedStatusForOrdersResult_OrderDatedStatus[] OrderDatedStatusField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSOrderService.GetDatedStatusForOrdersResult_OrderDatedStatus[] OrderDatedStatus
        {
            get
            {
                return this.OrderDatedStatusField;
            }
            set
            {
                this.OrderDatedStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDatedStatusForOrdersResult_OrderDatedStatus", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.OrderService")]
    public partial class GetDatedStatusForOrdersResult_OrderDatedStatus : object
    {
        
        private int OrderIdField;
        
        private int StatusIdField;
        
        private System.DateTime StatusTimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusTimeStamp
        {
            get
            {
                return this.StatusTimeStampField;
            }
            set
            {
                this.StatusTimeStampField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.e-logics.eu/WMSService", ConfigurationName="WMSOrderService.IOrderService")]
    public interface IOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IOrderService/ImportOrder", ReplyAction="http://www.e-logics.eu/WMSService/IOrderService/ImportOrderResponse")]
        System.Threading.Tasks.Task<WMSOrderService.ImportOrderResult> ImportOrderAsync(WMSOrderService.AuthenticationInfo Auth, WMSOrderService.ImportOrder_Order OrderToImport, bool Warnings, bool HoldOrderHandling);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IOrderService/GetOrderStatus", ReplyAction="http://www.e-logics.eu/WMSService/IOrderService/GetOrderStatusResponse")]
        System.Threading.Tasks.Task<WMSOrderService.GetOrderStatusResult> GetOrderStatusAsync(WMSOrderService.AuthenticationInfo Auth, string OrderReference, bool Warnings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IOrderService/GetDatedStatusForOrders", ReplyAction="http://www.e-logics.eu/WMSService/IOrderService/GetDatedStatusForOrdersResponse")]
        System.Threading.Tasks.Task<WMSOrderService.GetDatedStatusForOrdersResult> GetDatedStatusForOrdersAsync(WMSOrderService.AuthenticationInfo Auth, int[] OrderIds, System.DateTime StatusDate, bool Warnings, bool IncludeDeletedOrders);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IOrderServiceChannel : WMSOrderService.IOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<WMSOrderService.IOrderService>, WMSOrderService.IOrderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), OrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WMSOrderService.ImportOrderResult> ImportOrderAsync(WMSOrderService.AuthenticationInfo Auth, WMSOrderService.ImportOrder_Order OrderToImport, bool Warnings, bool HoldOrderHandling)
        {
            return base.Channel.ImportOrderAsync(Auth, OrderToImport, Warnings, HoldOrderHandling);
        }
        
        public System.Threading.Tasks.Task<WMSOrderService.GetOrderStatusResult> GetOrderStatusAsync(WMSOrderService.AuthenticationInfo Auth, string OrderReference, bool Warnings)
        {
            return base.Channel.GetOrderStatusAsync(Auth, OrderReference, Warnings);
        }
        
        public System.Threading.Tasks.Task<WMSOrderService.GetDatedStatusForOrdersResult> GetDatedStatusForOrdersAsync(WMSOrderService.AuthenticationInfo Auth, int[] OrderIds, System.DateTime StatusDate, bool Warnings, bool IncludeDeletedOrders)
        {
            return base.Channel.GetDatedStatusForOrdersAsync(Auth, OrderIds, StatusDate, Warnings, IncludeDeletedOrders);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IOrderService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrderService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IOrderService))
            {
                return new System.ServiceModel.EndpointAddress("https://www.e-logics.eu/WMS_WCF/OrderService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOrderService))
            {
                return new System.ServiceModel.EndpointAddress("https://www.e-logics.eu/WMS_WCF/OrderService.svc/basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IOrderService,
            
            BasicHttpBinding_IOrderService,
        }
    }
}
