//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSProductService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AuthenticationInfo : object
    {
        
        private string PasswordField;
        
        private string UserIdField;
        
        private decimal WarehouseIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WarehouseId
        {
            get
            {
                return this.WarehouseIdField;
            }
            set
            {
                this.WarehouseIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetStockInfoResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetStockInfoResult : object
    {
        
        private int CodeField;
        
        private string[] MessagesField;
        
        private WMSProductService.GetStockInfoResult_ProductStockListItem[] ProductStockListField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSProductService.GetStockInfoResult_ProductStockListItem[] ProductStockList
        {
            get
            {
                return this.ProductStockListField;
            }
            set
            {
                this.ProductStockListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetStockInfoResult_ProductStockListItem", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetStockInfoResult_ProductStockListItem : object
    {
        
        private int AmountOnStockField;
        
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmountOnStock
        {
            get
            {
                return this.AmountOnStockField;
            }
            set
            {
                this.AmountOnStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductsResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetProductsResult : object
    {
        
        private int CodeField;
        
        private string[] MessagesField;
        
        private WMSProductService.GetProductsResult_Product[] ProductsField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSProductService.GetProductsResult_Product[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductsResult_Product", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetProductsResult_Product : object
    {
        
        private bool BackOrderAllowedField;
        
        private WMSProductService.GetProductsResult_Catalogue CatalogueField;
        
        private System.DateTime CreationDateField;
        
        private string CustomerCodeField;
        
        private string DescriptionField;
        
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        private string[] FileAttachmentUrlsField;
        
        private string Filter1Field;
        
        private string Filter2Field;
        
        private string Filter3Field;
        
        private string Filter4Field;
        
        private string[] ImageUrlsField;
        
        private decimal MarketPriceField;
        
        private decimal MaximumOrderAmountField;
        
        private decimal MinimumStockNotificationAmountField;
        
        private decimal PricePerPieceField;
        
        private string ProductInfoField;
        
        private string ProductSpecsField;
        
        private bool ShippingCostIncludedField;
        
        private decimal VATRateField;
        
        private decimal WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BackOrderAllowed
        {
            get
            {
                return this.BackOrderAllowedField;
            }
            set
            {
                this.BackOrderAllowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSProductService.GetProductsResult_Catalogue Catalogue
        {
            get
            {
                return this.CatalogueField;
            }
            set
            {
                this.CatalogueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FileAttachmentUrls
        {
            get
            {
                return this.FileAttachmentUrlsField;
            }
            set
            {
                this.FileAttachmentUrlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter1
        {
            get
            {
                return this.Filter1Field;
            }
            set
            {
                this.Filter1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter2
        {
            get
            {
                return this.Filter2Field;
            }
            set
            {
                this.Filter2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter3
        {
            get
            {
                return this.Filter3Field;
            }
            set
            {
                this.Filter3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter4
        {
            get
            {
                return this.Filter4Field;
            }
            set
            {
                this.Filter4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageUrls
        {
            get
            {
                return this.ImageUrlsField;
            }
            set
            {
                this.ImageUrlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarketPrice
        {
            get
            {
                return this.MarketPriceField;
            }
            set
            {
                this.MarketPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaximumOrderAmount
        {
            get
            {
                return this.MaximumOrderAmountField;
            }
            set
            {
                this.MaximumOrderAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinimumStockNotificationAmount
        {
            get
            {
                return this.MinimumStockNotificationAmountField;
            }
            set
            {
                this.MinimumStockNotificationAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerPiece
        {
            get
            {
                return this.PricePerPieceField;
            }
            set
            {
                this.PricePerPieceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductInfo
        {
            get
            {
                return this.ProductInfoField;
            }
            set
            {
                this.ProductInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSpecs
        {
            get
            {
                return this.ProductSpecsField;
            }
            set
            {
                this.ProductSpecsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShippingCostIncluded
        {
            get
            {
                return this.ShippingCostIncludedField;
            }
            set
            {
                this.ShippingCostIncludedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VATRate
        {
            get
            {
                return this.VATRateField;
            }
            set
            {
                this.VATRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProductsResult_Catalogue", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetProductsResult_Catalogue : object
    {
        
        private string DescriptionField;
        
        private long IdField;
        
        private string[] ImageUrlsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageUrls
        {
            get
            {
                return this.ImageUrlsField;
            }
            set
            {
                this.ImageUrlsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCataloguesResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetCataloguesResult : object
    {
        
        private WMSProductService.GetCataloguesResult_Catalogue[] CataloguesField;
        
        private int CodeField;
        
        private string[] MessagesField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSProductService.GetCataloguesResult_Catalogue[] Catalogues
        {
            get
            {
                return this.CataloguesField;
            }
            set
            {
                this.CataloguesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCataloguesResult_Catalogue", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetCataloguesResult_Catalogue : object
    {
        
        private string DescriptionField;
        
        private decimal IdField;
        
        private string[] ImageUrlsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageUrls
        {
            get
            {
                return this.ImageUrlsField;
            }
            set
            {
                this.ImageUrlsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCatalogueProductsResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetCatalogueProductsResult : object
    {
        
        private int CodeField;
        
        private string[] MessagesField;
        
        private WMSProductService.GetCatalogueProductsResult_Product[] ProductsField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSProductService.GetCatalogueProductsResult_Product[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCatalogueProductsResult_Product", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class GetCatalogueProductsResult_Product : object
    {
        
        private bool BackOrderAllowedField;
        
        private System.DateTime CreationDateField;
        
        private string CustomerCodeField;
        
        private string DescriptionField;
        
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        private string[] FileAttachmentUrlsField;
        
        private string Filter1Field;
        
        private string Filter2Field;
        
        private string Filter3Field;
        
        private string Filter4Field;
        
        private string[] ImageUrlsField;
        
        private decimal MarketPriceField;
        
        private decimal MaximumOrderAmountField;
        
        private decimal MinimumStockNotificationAmountField;
        
        private decimal PricePerPieceField;
        
        private string ProductInfoField;
        
        private string ProductSpecsField;
        
        private bool ShippingCostIncludedField;
        
        private decimal VATRateField;
        
        private decimal WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BackOrderAllowed
        {
            get
            {
                return this.BackOrderAllowedField;
            }
            set
            {
                this.BackOrderAllowedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FileAttachmentUrls
        {
            get
            {
                return this.FileAttachmentUrlsField;
            }
            set
            {
                this.FileAttachmentUrlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter1
        {
            get
            {
                return this.Filter1Field;
            }
            set
            {
                this.Filter1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter2
        {
            get
            {
                return this.Filter2Field;
            }
            set
            {
                this.Filter2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter3
        {
            get
            {
                return this.Filter3Field;
            }
            set
            {
                this.Filter3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter4
        {
            get
            {
                return this.Filter4Field;
            }
            set
            {
                this.Filter4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageUrls
        {
            get
            {
                return this.ImageUrlsField;
            }
            set
            {
                this.ImageUrlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarketPrice
        {
            get
            {
                return this.MarketPriceField;
            }
            set
            {
                this.MarketPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaximumOrderAmount
        {
            get
            {
                return this.MaximumOrderAmountField;
            }
            set
            {
                this.MaximumOrderAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinimumStockNotificationAmount
        {
            get
            {
                return this.MinimumStockNotificationAmountField;
            }
            set
            {
                this.MinimumStockNotificationAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerPiece
        {
            get
            {
                return this.PricePerPieceField;
            }
            set
            {
                this.PricePerPieceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductInfo
        {
            get
            {
                return this.ProductInfoField;
            }
            set
            {
                this.ProductInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSpecs
        {
            get
            {
                return this.ProductSpecsField;
            }
            set
            {
                this.ProductSpecsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShippingCostIncluded
        {
            get
            {
                return this.ShippingCostIncludedField;
            }
            set
            {
                this.ShippingCostIncludedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VATRate
        {
            get
            {
                return this.VATRateField;
            }
            set
            {
                this.VATRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateProductResult", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class UpdateProductResult : object
    {
        
        private int CodeField;
        
        private WMSProductService.UpdateProductResult_ProductInfo ProductField;
        
        private bool SuccesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WMSProductService.UpdateProductResult_ProductInfo Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succes
        {
            get
            {
                return this.SuccesField;
            }
            set
            {
                this.SuccesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateProductResult_ProductInfo", Namespace="http://schemas.datacontract.org/2004/07/DataContracts.ProductService")]
    public partial class UpdateProductResult_ProductInfo : object
    {
        
        private decimal CostPriceField;
        
        private string CustomerCodeField;
        
        private string DescriptionField;
        
        private decimal MarketPriceField;
        
        private decimal PricePerPieceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostPrice
        {
            get
            {
                return this.CostPriceField;
            }
            set
            {
                this.CostPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode
        {
            get
            {
                return this.CustomerCodeField;
            }
            set
            {
                this.CustomerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarketPrice
        {
            get
            {
                return this.MarketPriceField;
            }
            set
            {
                this.MarketPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerPiece
        {
            get
            {
                return this.PricePerPieceField;
            }
            set
            {
                this.PricePerPieceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.e-logics.eu/WMSService", ConfigurationName="WMSProductService.IProductService")]
    public interface IProductService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IProductService/GetStockInfo", ReplyAction="http://www.e-logics.eu/WMSService/IProductService/GetStockInfoResponse")]
        System.Threading.Tasks.Task<WMSProductService.GetStockInfoResult> GetStockInfoAsync(WMSProductService.AuthenticationInfo Auth, bool Warnings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IProductService/GetProducts", ReplyAction="http://www.e-logics.eu/WMSService/IProductService/GetProductsResponse")]
        System.Threading.Tasks.Task<WMSProductService.GetProductsResult> GetProductsAsync(WMSProductService.AuthenticationInfo Auth, string LanguageCode, bool Warnings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IProductService/GetCatalogues", ReplyAction="http://www.e-logics.eu/WMSService/IProductService/GetCataloguesResponse")]
        System.Threading.Tasks.Task<WMSProductService.GetCataloguesResult> GetCataloguesAsync(WMSProductService.AuthenticationInfo Auth, string LanguageCode, bool Warnings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IProductService/GetCatalogueProducts", ReplyAction="http://www.e-logics.eu/WMSService/IProductService/GetCatalogueProductsResponse")]
        System.Threading.Tasks.Task<WMSProductService.GetCatalogueProductsResult> GetCatalogueProductsAsync(WMSProductService.AuthenticationInfo Auth, long CatalogueId, string LanguageCode, bool Warnings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.e-logics.eu/WMSService/IProductService/UpdateProduct", ReplyAction="http://www.e-logics.eu/WMSService/IProductService/UpdateProductResponse")]
        System.Threading.Tasks.Task<WMSProductService.UpdateProductResult> UpdateProductAsync(WMSProductService.AuthenticationInfo Auth, string CustomerCode, string Description, bool UpdateDescription, decimal PricePerPiece, bool UpdatePricePerPiece, decimal MarketPrice, bool UpdateMarketPrice, decimal CostPrice, bool UpdateCostPrice, bool Warnings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IProductServiceChannel : WMSProductService.IProductService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<WMSProductService.IProductService>, WMSProductService.IProductService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductServiceClient.GetBindingForEndpoint(endpointConfiguration), ProductServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WMSProductService.GetStockInfoResult> GetStockInfoAsync(WMSProductService.AuthenticationInfo Auth, bool Warnings)
        {
            return base.Channel.GetStockInfoAsync(Auth, Warnings);
        }
        
        public System.Threading.Tasks.Task<WMSProductService.GetProductsResult> GetProductsAsync(WMSProductService.AuthenticationInfo Auth, string LanguageCode, bool Warnings)
        {
            return base.Channel.GetProductsAsync(Auth, LanguageCode, Warnings);
        }
        
        public System.Threading.Tasks.Task<WMSProductService.GetCataloguesResult> GetCataloguesAsync(WMSProductService.AuthenticationInfo Auth, string LanguageCode, bool Warnings)
        {
            return base.Channel.GetCataloguesAsync(Auth, LanguageCode, Warnings);
        }
        
        public System.Threading.Tasks.Task<WMSProductService.GetCatalogueProductsResult> GetCatalogueProductsAsync(WMSProductService.AuthenticationInfo Auth, long CatalogueId, string LanguageCode, bool Warnings)
        {
            return base.Channel.GetCatalogueProductsAsync(Auth, CatalogueId, LanguageCode, Warnings);
        }
        
        public System.Threading.Tasks.Task<WMSProductService.UpdateProductResult> UpdateProductAsync(WMSProductService.AuthenticationInfo Auth, string CustomerCode, string Description, bool UpdateDescription, decimal PricePerPiece, bool UpdatePricePerPiece, decimal MarketPrice, bool UpdateMarketPrice, decimal CostPrice, bool UpdateCostPrice, bool Warnings)
        {
            return base.Channel.UpdateProductAsync(Auth, CustomerCode, Description, UpdateDescription, PricePerPiece, UpdatePricePerPiece, MarketPrice, UpdateMarketPrice, CostPrice, UpdateCostPrice, Warnings);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IProductService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProductService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IProductService))
            {
                return new System.ServiceModel.EndpointAddress("https://www.e-logics.eu/WMS_WCF/ProductService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProductService))
            {
                return new System.ServiceModel.EndpointAddress("https://www.e-logics.eu/WMS_WCF/ProductService.svc/basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IProductService,
            
            BasicHttpBinding_IProductService,
        }
    }
}
