// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMS.EntityFrameworkCore;

namespace RMS.Migrations
{
    [DbContext(typeof(RMSDbContext))]
    [Migration("20210817092937_Added_Campaign_Country")]
    partial class Added_Campaign_Country
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RMS.SBJ.CampaignProcesses.CampaignCountry", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("TenantId")
                    .HasColumnType("int");

                b.Property<long>("CampaignId")
                    .IsRequired()
                    .HasColumnType("bigint");

                b.Property<long>("CountryId")
                    .IsRequired()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("CampaignCountry");
            });
#pragma warning restore 612, 618
        }
    }
}
