// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMS.EntityFrameworkCore;

namespace RMS.Migrations
{
    [DbContext(typeof(RMSDbContext))]
    [Migration("20210805114151_Added_Handling_Batches")]
    partial class Added_Handling_Batches
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RMS.SBJ.HandlingBatch.HandlingBatchStatus", b
                =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");
                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HandlingBatchStatus");
                });

            modelBuilder.Entity("RMS.SBJ.HandlingBatch.HandlingBatchLineStatus", b
                =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("TenantId")
                    .HasColumnType("int");
                b.Property<string>("StatusCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("StatusDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("HandlingBatchLineStatus");
            });

            modelBuilder.Entity("RMS.SBJ.HandlingBatch.HandlingBatch", b
                =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("TenantId")
                    .HasColumnType("int");
                b.Property<DateTime>("DateCreated")
                    .IsRequired()
                    .HasColumnType("datetime");
                b.Property<string>("Remarks")
                    .HasColumnType("nvarchar(max)");
                b.Property<long>("CampaignTypeId")
                    .IsRequired()
                    .HasColumnType("bigint");
                b.Property<long>("HandlingBatchStatusId")
                    .IsRequired()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("HandlingBatch");
            });

            modelBuilder.Entity("RMS.SBJ.HandlingBatch.HandlingBatchHistory", b
                =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("TenantId")
                    .HasColumnType("int");
                b.Property<DateTime>("DateCreated")
                    .IsRequired()
                    .HasColumnType("datetime");
                b.Property<string>("Remarks")
                    .HasColumnType("nvarchar(max)");
                b.Property<long>("AbpUserId")
                    .IsRequired()
                    .HasColumnType("bigint");
                b.Property<long>("HandlingBatchId")
                    .IsRequired()
                    .HasColumnType("bigint");
                b.Property<long>("HandlingBatchStatusId")
                    .IsRequired()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("HandlingBatchHistory");
            });

            modelBuilder.Entity("RMS.SBJ.HandlingBatch.HandlingBatchLine", b
                =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("TenantId")
                    .HasColumnType("int");
                b.Property<string>("ExternalOrderId")
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("CustomerCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<long>("Quantity")
                    .IsRequired()
                    .HasColumnType("int");
                b.Property<long>("Amount")
                    .IsRequired()
                    .HasColumnType("decimal(18, 2)");
                b.Property<long>("ActivationCodeId")
                    .HasColumnType("bigint");
                b.Property<long>("HandlingBatchId")
                    .IsRequired()
                    .HasColumnType("bigint");
                b.Property<long>("PurchaseRegistrationId")
                    .IsRequired()
                    .HasColumnType("bigint");
                b.Property<long>("HandlingBatchLineStatusId")
                    .IsRequired()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("HandlingBatchLine");
            });

            modelBuilder.Entity("RMS.SBJ.HandlingBatch.HandlingBatchLineHistory", b
                =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("TenantId")
                    .HasColumnType("int");
                b.Property<DateTime>("DateCreated")
                    .IsRequired()
                    .HasColumnType("datetime");
                b.Property<string>("Remarks")
                    .HasColumnType("nvarchar(max)");
                b.Property<long>("AbpUserId")
                    .IsRequired()
                    .HasColumnType("bigint");
                b.Property<long>("HandlingBatchLineId")
                    .IsRequired()
                    .HasColumnType("bigint");
                b.Property<long>("HandlingBatchLineStatusId")
                    .IsRequired()
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("HandlingBatchLineHistory");
            });

            modelBuilder.Entity("RMS.SBJ.UniqueCodes.UniqueCode", b
                =>
            {
                b.Property<string>("Id")
                    .IsRequired()
                    .HasColumnType("nchar(10)");

                b.Property<bool>("Used")
                    .IsRequired()
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.ToTable("UniqueCode");
            });
#pragma warning restore 612, 618
        }
    }
}
